import { Department, Employee, LeaveRequest, RegDocument } from './types';

export const departments: Department[] = [
  { id: 'd1', name: 'ផ្នែកសង្គ្រោះបន្ទាន់ (Emergency)' },
  { id: 'd2', name: 'ផ្នែកវះកាត់ (Surgery)' },
  { id: 'd3', name: 'ផ្នែកកុមារ (Pediatrics)' },
  { id: 'd4', name: 'ផ្នែករដ្ឋបាល (Administration)' },
];

export const employees: Employee[] = [
  {
    id: 'e1',
    name: 'សុខ សាន្ត',
    gender: 'ប្រុស',
    departmentId: 'd1',
    position: 'វេជ្ជបណ្ឌិតសង្គ្រោះបន្ទាន់',
    phone: '012 345 678',
    joinDate: '2020-03-01',
    status: 'សកម្ម',
    resume: 'ប្រវត្តិរូបសង្ខេប_សាន្ត.pdf',
    contracts: [{ name: 'កុងត្រាចូលការងារចុងក្រោយ.pdf', url: '#', date: '2023-01-01' }],
    documents: [{ name: 'វិញ្ញាបនបត្រពេទ្យ.pdf', url: '#', date: '2020-02-15' }],
    role: 'Department Head',
    leaveBalances: {
      annualAllowed: 18,
      annualUsed: 5,
      sickAllowed: 15,
      sickUsed: 2,
      shortAllowed: 7,
      shortUsed: 0,
      personalAllowed: 7,
      personalUsed: 1,
      maternityAllowed: 0,
      maternityUsed: 0,
    },
  },
  {
    id: 'e2',
    name: 'ចាន់ ធីតា',
    gender: 'ស្រី',
    departmentId: 'd2',
    position: 'គិលានុបដ្ឋាយិកា',
    phone: '098 765 432',
    joinDate: '2021-06-15',
    status: 'សកម្ម',
    resume: 'ប្រវត្តិរូប_ធីតា.pdf',
    contracts: [{ name: 'កុងត្រា៣ឆ្នាំ.pdf', url: '#', date: '2021-06-15' }],
    documents: [],
    role: 'Staff',
    leaveBalances: {
      annualAllowed: 18,
      annualUsed: 1,
      sickAllowed: 15,
      sickUsed: 3,
      shortAllowed: 7,
      shortUsed: 0,
      personalAllowed: 7,
      personalUsed: 0,
      maternityAllowed: 90,
      maternityUsed: 0,
    },
  },
  {
    id: 'e3',
    name: 'រ៉េត ពិសិដ្ឋ',
    gender: 'ប្រុស',
    departmentId: 'd4',
    position: 'ប្រធានរដ្ឋបាល',
    phone: '011 222 333',
    joinDate: '2018-11-20',
    status: 'សកម្ម',
    resume: 'Resume_Piseth.pdf',
    contracts: [{ name: 'កុងត្រាអចិន្ត្រៃយ៍.pdf', url: '#', date: '2020-11-20' }],
    documents: [{ name: 'អត្តសញ្ញាណប័ណ្ណ.pdf', url: '#', date: '2018-11-15' }],
    role: 'Admin',
    leaveBalances: {
      annualAllowed: 18,
      annualUsed: 2,
      sickAllowed: 15,
      sickUsed: 1,
      shortAllowed: 7,
      shortUsed: 0,
      personalAllowed: 7,
      personalUsed: 2,
      maternityAllowed: 0,
      maternityUsed: 0,
    },
  },
  {
    id: 'e4',
    name: 'មករា ពេជ្រ',
    gender: 'ប្រុស',
    departmentId: 'd1',
    position: 'បុគ្គលិកបន្ទប់សង្គ្រោះ',
    phone: '012 999 888',
    joinDate: '2023-01-10',
    status: 'សកម្ម',
    role: 'Staff',
    resume: 'Resume_Makara.pdf',
    contracts: [{ name: 'កុងត្រា.pdf', url: '#', date: '2023-01-10' }],
    documents: [],
    leaveBalances: {
      annualAllowed: 18,
      annualUsed: 0,
      sickAllowed: 15,
      sickUsed: 0,
      shortAllowed: 7,
      shortUsed: 0,
      personalAllowed: 7,
      personalUsed: 0,
      maternityAllowed: 0,
      maternityUsed: 0,
    },
  },
];

export const leaveRequests: LeaveRequest[] = [
  {
    id: 'l1',
    employeeId: 'e2',
    startDate: '2024-05-10',
    endDate: '2024-05-12',
    type: 'ឈប់សម្រាកព្យាបាលជម្ងឺ',
    status: 'រង់ចាំ',
    reason: 'គ្រុនក្តៅ',
    isNewNotification: true,
    durationDays: 3,
  },
  {
    id: 'l2',
    employeeId: 'e1',
    startDate: '2024-06-01',
    endDate: '2024-06-05',
    type: 'ឈប់ប្រចាំឆ្នាំ',
    status: 'អនុម័ត',
    reason: 'ទៅលេងស្រុកកំណើត',
    isNewNotification: false,
    durationDays: 5,
  },
];

export const regDocuments: RegDocument[] = [
  {
    id: 'doc1',
    refNumber: '០១២/២៤/មព',
    title: 'លិខិតសុំបរិក្ខារពេទ្យបន្ថែម',
    type: 'លិខិតចេញ',
    date: '2024-05-01',
    status: 'បានអនុម័ត',
  },
  {
    id: 'doc2',
    refNumber: 'បក-០៥៥/២៤',
    title: 'ចូលរួមសិក្ខាសាលាវេជ្ជសាស្ត្រនៅខេត្តសៀមរាប',
    type: 'លិខិតបេសកកម្ម',
    date: '2024-05-15',
    status: 'ព្រាង',
    assigneeId: 'e1',
  },
  {
    id: 'doc3',
    refNumber: '០៩៩/២៤/កស',
    title: 'របាយការណ៍ប្រចាំខែ',
    type: 'លិខិតផ្ទៃក្នុង',
    date: '2024-04-30',
    status: 'បានបញ្ជូន',
  },
  {
    id: 'doc4',
    refNumber: '១០១/២៦/កស',
    title: 'កិច្ចសន្យាផ្គត់ផ្គង់ឱសថប្រចាំឆ្នាំ',
    type: 'កិច្ចសន្យា',
    date: '2025-06-10',
    expirationDate: '2026-06-15', // Expiring within 30 days from 2026-05-26
    status: 'បានអនុម័ត',
  },
  {
    id: 'doc5',
    refNumber: '១០២/២៥/កស',
    title: 'កិច្ចសន្យាជួលទីតាំង',
    type: 'កិច្ចសន្យា',
    date: '2024-01-01',
    expirationDate: '2026-04-10', // Already expired
    status: 'បានអនុម័ត',
  },
];
